replicaCount: 1

image:
  repository: nodered/node-red
  tag: 3.1
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 1880

resources:
  limits:
    cpu: 500m
    memory: 256Mi
  requests:
    cpu: 250m
    memory: 128Mi

persistence:
  enabled: true
  accessMode: ReadWriteOnce
  size: 1Gi
  storageClass: ""

ingress:
  enabled: false
  annotations: {}
  hosts:
    - host: chart-example.local
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls: []

nodeSelector: {}
tolerations: []
affinity: {}
