apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-node-red
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 1880
  selector:
    app: {{ .Chart.Name }}
